org.gradle.jvmargs=-Xmx8g
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
softconfig.group=io.github.akinsoft.softconfig
softconfig.version=4.8.0-SNAPSHOT
softconfig.compatibilityBaseline=4.7.2
softconfig.compatibilityBaselineGroup=org.notenoughupdates.moulconfig
detekt.version=2.0.0-alpha.2
checkstyle.version=10.21.4
