org.gradle.jvmargs=-Xmx8g
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
softconfig.group=io.github.akinsoft.softconfig
softconfig.version=4.8.3-SNAPSHOT
softconfig.activeMinecraftVersions=1.21.11,26.1,26.2
softconfig.compatibilityBaseline=4.8.2
softconfig.compatibilityBaselineGroup=io.github.akinsoft.softconfig
detekt.version=2.0.0-alpha.2
checkstyle.version=10.21.4
