site_name: SoftConfig
site_description: A compatibility-focused configuration library for Minecraft mods
site_author: SoftConfig contributors
site_url: https://akinsoft.github.io/SoftConfig/

repo_name: Akinsoft/SoftConfig
repo_url: https://github.com/Akinsoft/SoftConfig
edit_uri: edit/main/src/doc/docs/
copyright: 'Copyright &copy; 2026 SoftConfig contributors and MoulConfig contributors'

plugins:
  - zettelkasten

theme:
  name: zettelkasten-solarized-light
  social:
    - type: 'github'
      link: 'https://github.com/Akinsoft/SoftConfig'
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top

nav:
  - Home:
      - index.md
  - Config:
      - config/index.md
